name: Deploy to Truehost (FTP)
on:
  push:
    branches: [main] # or any branch you prefer
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          # optional: only upload changed files
          local-dir: .
          remote-dir: /public_html/cicd.bbismkd.com.ng/ # adjust if your site lives elsewhere
          exclude: |
            .git*
            .github*
            README.md
            .env
