name: Deploy Website to cPanel on Push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Sync files via FTP
      - name: Sync Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          # optional: only upload changed files
          local-dir: ./
          server-dir: /public_html/cicd.bbismkd.com.ng/ # adjust if your site lives elsewhere
          exclude: .git,README.md
